modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="unusualprehistory"
version="1.2.0"
displayName= "Unusual Prehistory"
logoFile= "examplemod.png"
credits= "Thanks to Fred, Omatypaty, and Crydigo for textures! Thanks to skyjay1#2076 for help on GUI code! Thanks to Scouter456 and Codyy for Coding Help! Thanks to Shroomy for sound help!"
authors= "Peeko32213"
description='''
A Mod that adds a variety of prehistoric creatures and a way to revive them
'''

[[dependencies.examplemod]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.examplemod]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.geckolib]]
modId="geckolib3"
mandatory=true
versionRange="[3.1.27,3.1.39]"
ordering="BEFORE"
side="BOTH"

